#!/usr/bin/python

import sys
import os
from markdown2 import markdown
import webbrowser
from tempfile import NamedTemporaryFile

UNICODE_META = '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>'
CSS_TAG	 = '<link href="http://kevinburke.bitbucket.org/markdowncss/markdown.css" rel="stylesheet"></link>'

def open_md_file(path):
	with open(path, 'r') as mdfile:
		md = mdfile.read()
	
	html = UNICODE_META + CSS_TAG + markdown(md)
	basename = os.path.basename(path).split('.')[0]
	suffix = '_' + basename + '.html'
		
	with NamedTemporaryFile(mode='w', prefix='', suffix=suffix, delete=False) as tmp:
		tmp.write(html.encode('utf8'))
		
	webbrowser.open("file://" + tmp.name, 2)
	#os.remove(tmp.name) seems not to work, but whatevs
	
if __name__ == '__main__':
	files = sys.argv[1:]
	for f in files: 
		open_md_file(f)
		
